# ==============================
# 🤖 AI FEATURES (GEMINI SETUP)
# ==============================
import streamlit as st
import google.generativeai as genai
import os

# Load API key safely
api_key = os.getenv("GEMINI_API_KEY")

# Check if key exists
if not api_key:
    st.error("❌ GEMINI API KEY missing! Please add it in Streamlit Secrets.")
else:
    genai.configure(api_key=api_key)

   # Load model
model = genai.GenerativeModel("gemini-2.0-flash")

import pandas as pd

# Load dataset
df = pd.read_csv("netflix.csv")
filtered_df = df
# UI separator
st.markdown("---")
# Tabs
tab1, tab2, tab3 = st.tabs(["AI Insights", "Recommendations", "AI Chat"])


# ==============================
# 🔍 AI INSIGHTS
# ==============================
with tab1:
    if st.button("Generate AI Insights"):
        try:
            # Check data
            if filtered_df.empty:
                st.warning("No data available for analysis.")
            else:
                sample_data = filtered_df.head(20).to_string()

                prompt = f"""
                You are a data analyst.

                Analyze this Netflix dataset:

                {sample_data}

                Give 5 key insights in simple and clear points.
                """

                response = model.generate_content(prompt)

                # Safe output handling
                if response and hasattr(response, "text"):
                    st.success(response.text)
                else:
                    st.warning("No response generated by AI.")

        except Exception as e:
            st.error(f"Error: {e}")
# ==============================
# 🎯 RECOMMENDATIONS
# ==============================
with tab2:
    genre_input = st.text_input("Enter Genre (Comedy, Drama, Horror)")

    if st.button("Get Recommendations"):
        try:
            prompt = f"Suggest 5 Netflix {genre_input} movies with short description."

            response = model.generate_content(prompt)
            st.success(response.text)

        except Exception as e:
            st.error(f"Error: {e}")


# ==============================
# 💬 AI CHATBOT
# ==============================
with tab3:
    user_q = st.chat_input("Ask anything about Netflix data...")

    if user_q:
        try:
            data_sample = df.head(20).to_string()

            prompt = f"""
            You are a Netflix data assistant.

            Dataset sample:
            {data_sample}

            Question: {user_q}
            """

            response = model.generate_content(prompt)
            st.chat_message("assistant").write(response.text)

        except Exception as e:
            st.error(f"Error: {e}")
